language: node_js

node_js:
- '0.12'
- '0.10'
- 'latest'

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g npm

script:
- npm run lint
- npm test -- --browsers PhantomJS
